services:
  # Backend API Service
  - type: web
    name: interview-hub-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: interview-hub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BREVO_SMTP_USER
        sync: false
      - key: BREVO_SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        value: noreply@interviewhub.iiita.ac.in
      - key: FRONTEND_URL
        value: https://interviewhub-cyan.vercel.app
      - key: GEMINI_API_KEY
        sync: false

# PostgreSQL Database
databases:
  - name: interview-hub-db
    databaseName: interview_hub
    user: interview_hub_user